<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="1">

  <testsuite name="StackOverflow"
    errors="1" failures="0" hostname="" id="" package="StackOverflow" skipped="0"
    tests="1" time="208.9" timestamp="">
  
    <testcase name="Test StackOverflow Search" classname="StackOverflow" time="208.9" assertions="8">

    

    

    

    

    

    

    
<system-out>[[ATTACHMENT|/Users/tonyprater/Documents/Testing/tests_output/screenshots/StackOverflow/Test-StackOverflow-Search_FAILED_Jan-24-2020-161427-GMT-0500-(Eastern-Standard.png]]</system-out>
    
    </testcase>
  

  
    <system-err>
      [0;31m  TimeoutError: An error occurred while running .setValue() command on &lt;input[type=text]&gt;: 
   {&#34;status&#34;:-1,&#34;state&#34;:&#34;&#34;,&#34;value&#34;:null,&#34;errorStatus&#34;:&#34;&#34;,&#34;error&#34;:&#34;An unknown error has occurred.&#34;}[0m
[0;90m       at processTicksAndRejections (internal/process/task_queues.js:93:5)[0m
    </system-err>
  

  
  </testsuite>
</testsuites>
